### ISSUE TITLE
labels, margin, padding need to be improved for the modal of asking query at the discussion forum

### ISSUE THREAD

**Issue by soorajarsn** [codebiet/website#5]
![ask_question_modal](https://user-images.githubusercontent.com/52688472/135460358-dd09a3d4-575a-48b1-8969-4bfbe6a218c8.png)

- labels(Short but descriptive, Provide a detailed description to make it easier for others to reply) are misplaced, they need to be on top of input fields...

- need to add a label for tag input(the last input field of the modal)

**Comment by singhsharad529** [comment]
Hi sir i want to work on this issue .
